# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!
branch = ENV['sha']

target 'CocoaPodsDynamicExample' do
  pod 'WabiRealm', git: 'https://github.com/Wabi-Studios/wabi-realm.git', branch: branch, submodules: true
end

target 'CocoaPodsDynamicExampleTests' do
  pod 'WabiRealm', git: 'https://github.com/Wabi-Studios/wabi-realm.git', branch: branch, submodules: true
end
