# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

branch = ENV['sha']

target 'CocoaPodsExample' do
  pod 'WabiRealm', git: 'https://github.com/Wabi-Studios/wabi-realm.git', branch: branch, submodules: true
end

target 'CocoaPodsExampleTests' do
  pod 'WabiRealm/Headers', git: 'https://github.com/Wabi-Studios/wabi-realm.git', branch: branch, submodules: true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
    end
  end
end
